In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/organizations/mlg-ulb/creditcardfraud/creditcard.csv

In [2]:
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/organizations/mlg-ulb/creditcardfraud/creditcard.csv

In [3]:
import pandas as pd

fraud = pd.read_csv("/kaggle/input/datasets/organizations/mlg-ulb/creditcardfraud/creditcard.csv")

fraud.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
!pip install duckdb

Requirement already satisfied: duckdb in /usr/local/lib/python3.12/dist-packages (1.3.2)

In [5]:
import duckdb

In [6]:
duckdb.sql("""
SELECT *
FROM fraud
LIMIT 5;
""").df()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [7]:
duckdb.sql("""
SELECT
    COUNT(*) AS Total_Transactions
FROM fraud;
""").df()

   Total_Transactions
0              284807

In [8]:
duckdb.sql("""
SELECT
    Class,
    COUNT(*) AS Total
FROM fraud
GROUP BY Class;
""").df()

   Class   Total
0      0  284315
1      1     492

In [9]:
duckdb.sql ("""
SELECT 
ROUND (100.0 * SUM(Class)/COUNT(*),4) AS Fraud_Percentage
FROM fraud;
""").df()

   Fraud_Percentage
0            0.1727

In [10]:
duckdb.sql("""
SELECT
    ROUND(AVG(Amount),2) AS Average_Amount
FROM fraud;
""").df()

   Average_Amount
0           88.35

In [11]:
duckdb.sql("""
SELECT 
  MAX (AMOUNT) AS Highest_Transaction
  FROM fraud;
  """).df()

   Highest_Transaction
0             25691.16

In [12]:
duckdb.sql("""
SELECT
Amount, Class
FROM fraud
ORDER BY Amount DESC
LIMIT 10;
""").df()

     Amount  Class
0  25691.16      0
1  19656.53      0
2  18910.00      0
3  12910.93      0
4  11898.09      0
5  11789.84      0
6  10199.44      0
7  10000.00      0
8   8790.26      0
9   8787.00      0

In [13]:
duckdb.sql("""
SELECT
    ROUND(AVG(Amount),2) AS Average_Fraud_Amount
FROM fraud
WHERE Class = 1;
""").df()

   Average_Fraud_Amount
0                122.21

In [14]:
duckdb.sql("""
SELECT
    ROUND(AVG(Amount),2) AS Average_Genuine_Amount
FROM fraud
WHERE Class = 0;
""").df()

   Average_Genuine_Amount
0                   88.29

In [15]:
duckdb.sql("""
SELECT
    Amount,
    Class
FROM fraud
WHERE Amount >
(
    SELECT AVG(Amount)
    FROM fraud
)
ORDER BY Amount DESC
LIMIT 20;
""").df()

      Amount  Class
0   25691.16      0
1   19656.53      0
2   18910.00      0
3   12910.93      0
4   11898.09      0
5   11789.84      0
6   10199.44      0
7   10000.00      0
8    8790.26      0
9    8787.00      0
10   8360.00      0
11   8182.70      0
12   7879.42      0
13   7862.39      0
14   7766.60      0
15   7712.43      0
16   7636.30      0
17   7583.32      0
18   7541.70      0
19   7429.15      0

In [16]:
duckdb.sql("""
SELECT
    COUNT(*) AS High_Value_Fraud
FROM fraud
WHERE Class = 1
AND Amount > 1000;
""").df()

   High_Value_Fraud
0                 9

In [17]:
duckdb.sql("""
SELECT *
FROM fraud
WHERE Class = 1
LIMIT 10;
""").df()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,406.0,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1
1,472.0,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1
2,4462.0,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1
3,6986.0,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1
4,7519.0,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1
5,7526.0,0.008430,4.137837,-6.240697,6.675732,0.768307,-3.353060,-1.631735,0.154612,-2.795892,...,0.364514,-0.608057,-0.539528,0.128940,1.488481,0.507963,0.735822,0.513574,1.00,1
6,7535.0,0.026779,4.132464,-6.560600,6.348557,1.329666,-2.513479,-1.689102,0.303253,-3.139409,...,0.370509,-0.576752,-0.669605,-0.759908,1.605056,0.540675,0.737040,0.496699,1.00,1
7,7543.0,0.329594,3.712889,-5.775935,6.078266,1.667359,-2.420168,-0.812891,0.133080,-2.214311,...,0.156617,-0.652450,-0.551572,-0.716522,1.415717,0.555265,0.530507,0.404474,1.00,1
8,7551.0,0.316459,3.809076,-5.615159,6.047445,1.554026,-2.651353,-0.746579,0.055586,-2.678679,...,0.208828,-0.511747,-0.583813,-0.219845,1.474753,0.491192,0.518868,0.402528,1.00,1
9,7610.0,0.725646,2.300894,-5.329976,4.007683,-1.730411,-1.732193,-3.968593,1.063728,-0.486097,...,0.589669,0.109541,0.601045,-0.364700,-1.843078,0.351909,0.594550,0.099372,1.00,1

In [18]:
duckdb.sql("""
SELECT *
FROM fraud
WHERE Class = 0
LIMIT 10;
""").df()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,...,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0
8,7.0,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,...,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0
9,9.0,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,...,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0

In [19]:
duckdb.sql("""
SELECT
    Amount,
    Class
FROM fraud
WHERE Amount > 500
ORDER BY Amount DESC;
""").df()

        Amount  Class
0     25691.16      0
1     19656.53      0
2     18910.00      0
3     12910.93      0
4     11898.09      0
...        ...    ...
9137    500.18      0
9138    500.11      0
9139    500.06      0
9140    500.06      0
9141    500.04      0

[9142 rows x 2 columns]

In [20]:
duckdb.sql("""
SELECT
    Amount,
    Class
FROM fraud
WHERE Amount < 10;
""").df()

       Amount  Class
0        2.69      0
1        3.67      0
2        4.99      0
3        3.68      0
4        7.80      0
...       ...    ...
97309    9.87      0
97310    5.49      0
97311    2.68      0
97312    2.69      0
97313    0.77      0

[97314 rows x 2 columns]

In [21]:
duckdb.sql("""
SELECT
    COUNT(*) AS Total_Transactions
FROM fraud
WHERE Amount > 1000;
""").df()

   Total_Transactions
0                2940

In [22]:
duckdb.sql("""
SELECT
    ROUND(AVG(Amount),2) AS Average_Amount
FROM fraud
WHERE Amount > 100;
""").df()

   Average_Amount
0          348.37

In [23]:
duckdb.sql("""
SELECT
    Amount,
    Class
FROM fraud
ORDER BY Amount ASC
LIMIT 10;
""").df()

   Amount  Class
0     0.0      0
1     0.0      0
2     0.0      0
3     0.0      0
4     0.0      0
5     0.0      0
6     0.0      0
7     0.0      1
8     0.0      0
9     0.0      0

In [24]:
duckdb.sql("""
SELECT
    CASE
        WHEN Amount < 100 THEN 'Low'
        ELSE 'High'
    END AS Category,
    COUNT(*) AS Total_Transactions
FROM fraud
GROUP BY Category;
""").df()

  Category  Total_Transactions
0      Low              227422
1     High               57385

In [25]:
duckdb.sql("""
SELECT
    Amount
FROM fraud
WHERE Class = 1
ORDER BY Amount DESC
LIMIT 10;
""").df()

    Amount
0  2125.87
1  1809.68
2  1504.93
3  1402.16
4  1389.56
5  1354.25
6  1335.00
7  1218.89
8  1096.99
9   996.27

In [26]:
duckdb.sql("""
SELECT
    ROUND(SUM(Amount),2) AS Total_Fraud_Amount
FROM fraud
WHERE Class = 1;
""").df()

   Total_Fraud_Amount
0            60127.97